'''
Each new term in the Fibonacci sequence is generated by adding the previous two
terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
'''

def sumEvenFibo(limit):
    x1 = 1
    x2 = 2
    # print x1,x2,
    s = 2    
    i = 3
    while i<=limit:
        r = x1 + x2
        # print r,
        if i%2==0:
            s+=r
        x1 = x2
        x2 = r
        i+=1
    return s

l = input('Enter limit: ')
tot = sumEvenFibo(l)
# print ''
print tot
